AXUM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('allauth.urls')),
    
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from .views import Home, ProfileList, ProfileCreate, Watch, ShowMovieDetail, ShowMovie

app_name='core'

urlpatterns = [
    path('', Home.as_view()),
    path('profile/',ProfileList.as_view(),name='profile_list'),
    path('profile/create/',ProfileCreate.as_view(),name='profile_create'),
    path('watch/<str:profile_id>/',Watch.as_view(),name='watch'),
    path('movie/detail/<str:movie_id>/',ShowMovieDetail.as_view(),name='show_det'),
    path('movie/play/<str:movie_id>/',ShowMovie.as_view(),name='play')
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid

AGE_CHOICES = (
    ('All', 'All'),
    ('Kids', 'Kids')
)

MOVIE_CHOICES = (
    ('seasonal', 'Seasonal'),
    ('single', 'Single'),
)

GENER_CHOICES = (
    ('action', 'action'),
    ('comedy', 'comedy'),
    ('romantic', 'romantic'),
    ('amharic', 'amharic'),
    ('drama', 'drama'),
)


class CustomUser(AbstractUser):
    profiles = models.ManyToManyField('profile', blank=True)


class Profile(models.Model):
    name = models.CharField(max_length=225)
    age_limit = models.CharField(max_length=10, choices=AGE_CHOICES)
    uuid = models.UUIDField(default=uuid.uuid4)


class Movie(models.Model):
    title: str = models.CharField(max_length=225)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    uuid = models.UUIDField(default=uuid.uuid4)
    type = models.CharField(max_length=10, choices=MOVIE_CHOICES)
    videos = models.ManyToManyField('Video')
    flyer = models.ImageField(upload_to='flyers')
    age_limit = models.CharField(max_length=10, choices=AGE_CHOICES)
    gener = models.CharField(
        max_length=10, choices=GENER_CHOICES, default='action')


class Video(models.Model):
    title: str = models.CharField(max_length=225, blank=True, null=True)
    file = models.FileField(upload_to='movies')

core/forms.py
from django.forms import ModelForm
from .models import Profile

class ProfileForm(ModelForm):
    class Meta:
        model=Profile
        exclude=['uuid']

core/views.py
from core.models import Profile, Movie
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import ProfileForm


class Home(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('core:profile_list')
        return render(request, 'index.html')


@method_decorator(login_required, name='dispatch')
class ProfileList(View):
    def get(self, request, *args, **kwargs):
        profiles = request.user.profiles.all()
        return render(request, 'profileList.html', {
            'profiles': profiles
        })


@method_decorator(login_required, name='dispatch')
class ProfileCreate(View):
    def get(self, request, *args, **kwargs):
        form = ProfileForm()

        return render(request, 'profileCreate.html', {
            'form': form
        })

    def post(self, request, *args, **kwargs):
        form = ProfileForm(request.POST or None)

        if form.is_valid():
            profile = Profile.objects.create(**form.cleaned_data)
            if profile:
                request.user.profiles.add(profile)
                return redirect('core:profile_list')

        return render(request, 'profileCreate.html', {
            'form': form
        })


@method_decorator(login_required, name='dispatch')
class Watch(View):
    def get(self, request, profile_id, *args, **kwargs):
        try:
            profile = Profile.objects.get(uuid=profile_id)
            movies = Movie.objects.filter(age_limit=profile.age_limit)

            if profile not in request.user.profiles.all():
                return redirect(to='core:profile_list')

            return render(request, 'movieList.html', {
                'movies': movies,
            })
        except Profile.DoesNotExist:
            return redirect(to='core:profile_list')


@method_decorator(login_required, name='dispatch')
class ShowMovieDetail(View):
    def get(self, request, movie_id, *args, **kwargs):
        try:

            movie = Movie.objects.get(uuid=movie_id)

            return render(request, 'movieDetail.html', {
                'movie': movie
            })
        except Movie.DoesNotExist:
            return redirect('core:profile_list')


@method_decorator(login_required, name='dispatch')
class ShowMovie(View):
    def get(self, request, movie_id, *args, **kwargs):
        try:

            movie = Movie.objects.get(uuid=movie_id)

            movie = movie.videos.values()

            return render(request, 'showMovie.html', {
                'movie': list(movie)
            })
        except Movie.DoesNotExist:
            return redirect('core:profile_list')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Axum - {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %} ">
    {% block others %}{% endblock others %}
</head>
<body class="bg-black text-gray-100 font-primary">
    {% block content %}

    {% endblock content %}
    <script>
        const nav = document.querySelector('nav')

        document.addEventListener("scroll",e=>{
            
            if(scrollY>100){
                nav.classList.add('bg-gray-900')
          
            }else{
                nav.classList.remove('bg-gray-900')
                
            }
        })

    </script>
</body >
</html>

templates/index.html
{%extends 'base.html' %}
{% load static %}
{% block title %}
    Home
{% endblock title %}

{% block others %}
<script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
{% endblock others %}

{% block content %}
    

{% include "partials/navbar.html" %}
    <header class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('/static/background_axum.jpg');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
                Unlimited movies, TV shows, and more.
            </h1>
            <h3 class="text-xl md:text-xl py-5">
                Watch the latest movies from anywhere. 
            </h3>
            <h4 class="text-sm md:text-lg pb-3">
                Ready to watch? 
            </h4>

            <div class="w-full flex justify-center">
                <div class="flex justify-center items-center w-11/12 md:w-10/12">
                    
                    <a href="{% url 'account_login' %}">
                        <button class="bg-primary_red font-medium md:font-normal flex justify-center items-center py-4 px-2 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl">
                            <span>
                                Get Started
                            </span>
                            <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </header>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Enjoy on your TV.
            </h2>
            <h5 class="md:text-xl text-lg">
                Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'tv.png' %}" class="w-8/12" alt="">
        </div>
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class='md:w-1/2 flex justify-center items-center order-2'>
            <img src="{% static 'mobile-0819.jpg' %}" class="w-8/12" alt="">
        </div>

        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                 Enjoy your life 
            </h2>
            <h5 class="md:text-xl text-lg">
                with our Unlimite movies
            </h5>
        </div>
        
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Create profiles for kids.
            </h2>
            <h5 class="md:text-xl text-lg">
                Send kids on adventures with their favorite characters in a space made just for them—free with your membership.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'axum_kid.png' %}" class="w-8/12" alt="">
        </div>
    </section>
    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">
            
            <li>&copy; 2023 Semester Project</li>
        </ul>
    </footer>

    {% endblock content %}

templates/movieDetail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Axum
{% endblock title %}

{% block others %}
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>

{% endblock others %}
{% block content %}


    {% include 'partials/navbar.html' %}

    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url('{{movie.flyer.url}}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{movie.title}}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{movie.description }}
                    
                </p>
                <div class="flex my-4">
                    <a href="{% url 'core:play' movie_id=movie.uuid %}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style="color:black">
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
                    </a>
                    
                </div>
            </div>
        </section> 
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                {% if movie.type == 'seasonal' %}
                <div style='margin-top:2rem;margin-bottom:2rem;'>
                
                    <h2 class="text-gray-200 text-3xl font-medium">
                        Episode
                    </h2>
                    {% for episode in movie.videos.all %}
                        <h3 class='text-lg'>
                            <a href="{% url 'core:play' movie_id=movie.uuid %}?epi={{forloop.counter0}}">
                            
                            {{forloop.counter}} - {{episode.title}}
                            </a>
                        </h3>
                    {% endfor %}
                
                </div>
                {% endif %}
                <h2 class="text-gray-200 text-3xl font-medium">
                    Description
                </h2>
                <div class="flex justify-center  items-center min-w-full  movie_lis">
                    <p class="text-gray-100 text-lg">

                        {{movie.description}}
                    </p>
                </div>
            </div>
        </section>
        
    </main>
{% endblock content %}

templates/movieList.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
AXUM
{% endblock title %}

{% block others %}
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>

{% endblock others %}
{% block content %}


    {% include 'partials/navbar.html' %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('/static/movie.webp');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    Vikings
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Delectus repellendus odit perspiciatis nostrum culpa exercitationem quis. Ab obcaecati odio minus. Dolorum sapiente eaque, repellendus ea fugiat amet fuga libero at!
                </p>
                <div class="flex my-4">
                    <a href="{% url 'core:play' movie_id='cdcf02b8-b028-4ad4-a68c-27bc9c28fa43' %}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style="color:black">
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
                    </a>

                        <a href="{% url 'core:show_det' movie_id='cdcf02b8-b028-4ad4-a68c-27bc9c28fa43' %}">
                        <button class="ml-4 text-white flex items-center bg-gray-500 bg-opacity-80 py-2 px-5 rounded-md">
                        <ion-icon name="information-circle-outline" class="text-2xl" ></ion-icon>
                        <span class="ml-3 font-medium">
                            More Info
                        </span>
                    </button>
                    </a>
                </div>
            </div>
        </section> 
        <section class='bg-primary_black   flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    ACTION
                </h2>
                <div class="flex justify-center items-center min-w-full  movie_lis">

                    {% for movie in movies %}
                    {% if movie.gener == 'action'  %}
                    <a href="{% url 'core:show_det' movie_id=movie.uuid %}">
                    <div class="flex-shrink-0  h-40 m-4  bg-blue-500 rounded-md cursor-pointer overflow-hidden w-40" >
                        <img src="{{movie.flyer.url}}" class="w-full h-full " alt="">
                    </div>

                    </a>
                    {% endif %}
                    {% endfor %}

                </div>

                <h2 class="text-gray-200 text-2xl font-medium">
                    COMEDY
                </h2>
                <div class="flex justify-center  items-center min-w-full  movie_lis">

                    {% for movie in movies %}
                    {% if movie.gener == 'comedy' %}
                    <a href="{% url 'core:show_det' movie_id=movie.uuid %}">
                    <div class="flex-shrink-0  h-40 m-4  bg-blue-500 rounded-md cursor-pointer overflow-hidden w-40" >
                        <img src="{{movie.flyer.url}}" class="w-full h-full " alt="">
                    </div>

                    </a>
                    {% endif %}
                    {% endfor %}

                </div>

                <h2 class="text-gray-200 text-2xl font-medium">
                    ROMANTIC
                </h2>
                <div class="flex justify-center  items-center min-w-full  movie_lis">

                    {% for movie in movies %}
                    {% if movie.gener == 'romantic' %}
                    <a href="{% url 'core:show_det' movie_id=movie.uuid %}">
                    <div class="flex-shrink-0  h-40 m-4  bg-blue-500 rounded-md cursor-pointer overflow-hidden w-40" >
                        <img src="{{movie.flyer.url}}" class="w-full h-full " alt="">
                    </div>

                    </a>
                    {% endif %}
                    {% endfor %}

                </div>

                <h2 class="text-gray-200 text-2xl font-medium">
                    AMHARIC
                </h2>
                <div class="flex justify-center  items-center min-w-full  movie_lis">

                    {% for movie in movies %}
                    {% if movie.gener == 'amharic' %}
                    <a href="{% url 'core:show_det' movie_id=movie.uuid %}">
                    <div class="flex-shrink-0  h-40 m-4  bg-blue-500 rounded-md cursor-pointer overflow-hidden w-40" >
                        <img src="{{movie.flyer.url}}" class="w-full h-full " alt="">
                    </div>

                    </a>
                    {% endif %}
                    {% endfor %}

                </div>

                <h2 class="text-gray-200 text-2xl font-medium">
                    DRAMA
                </h2>
                <div class="flex justify-center  items-center min-w-full  movie_lis">

                    {% for movie in movies %}
                    {% if movie.gener == 'drama' %}
                    <a href="{% url 'core:show_det' movie_id=movie.uuid %}">
                    <div class="flex-shrink-0  h-40 m-4  bg-blue-500 rounded-md cursor-pointer overflow-hidden w-40" >
                        <img src="{{movie.flyer.url}}" class="w-full h-full " alt="">
                    </div>

                    </a>
                    {% endif %}
                    {% endfor %}

                </div>
                
            </div>

            
        </section>
        
    </main>
{% endblock content %}

templates/partials/navbar.html
{% load static %}
<nav class="flex text-gray-100 justify-between items-center py-3 px-4 fixed w-full z-50">
        <div class="w-6/12">
            <a href='/'>
            
            <img src="{% static 'images.png' %}" alt="logo" class="w-5/12 md:w-2/12">
            </a>
        </div>

        {% if AUTH != 'false'  %}
            {% if request.user.is_authenticated %}
            <div>
            <form action="{% url 'account_logout' %}" method="post">
                {% csrf_token %}
                <button class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                    Logout
                </button>
            </form>
            </div>
            {% else %}
            <div>
            <a href="{% url 'account_login' %}">

                <button class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                    Sign In 
                </button>
            </a>
            </div>
            {% endif %}
        {% endif %}
    </nav>

templates/profileCreate.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Profile
{% endblock title %}

{% block content %}
    {% include 'partials/navbar.html' %}
    <section class='bg-primary_black min-h-screen py-20 md:py-32 flex-col flex items-center' style="background-image:url('static/background_netflix.jpg')">
        <div class="flex flex-wrap justify-center  w-10/12  md:w-6/12">
            <form method="post" class="w-full md:w-8/12 bg-gray-900 p-5 rounded-lg">
                <h1 class="text-4xl text-center text-gray-100 font-medium">
                    Create A Profile
                </h1>
                {% csrf_token %}
                <div class="my-4"> 
                    <Label class='text-lg text-gray-200 font-medium mb-3'>
                        Profile Name
                    </Label>
                    <input required class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full" type="text" name="name" id="id_name" placeholder="Profile name">
                </div>
                <div class="my-4"> 
                    <Label class='text-lg text-gray-200 font-medium mb-3'>
                        Maturity Level
                    </Label>
                    <select class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full"  name="age_limit" id="id_age_limit" >
                        <option value="All">All</option>
                        <option value="Kids">Kids</option>
                       
                    </select>
                </div>
                <div class="flex justify-center items-center">
                    <button class="px-4 py-2 rounded-md outline-none bg-primary_red text-gray-100">Create Profile</button>
                </div>
            </form> 
        </div>
        
    </section>

{% endblock content %}

templates/profileList.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Profile
{% endblock title %}

{% block content %}
    {% include 'partials/navbar.html' %}
    <section class='bg-primary_black min-h-screen py-20 md:py-0 flex-col flex justify-center items-center'>
        <h2 class="text-center font-medium text-5xl my-4 text-gray-100">
            Who's watching ?
        </h2>

        <div class="flex flex-wrap justify-center items-center w-10/12  md:w-6/12">
        {% for profile in profiles %}
            <a href="{% url 'core:watch' profile_id=profile.uuid %}">
            
                <div class="w-32 h-32 m-4  bg-blue-500 flex justify-center items-center flex-col rounded-md cursor-pointer">
                    <p class='text-6xl'>
                        {{profile.name | slice:":1"}}
                    </p>
                    <p class='text-lg'>
                        {{profile.name}}
                    </p>
                </div>
            </a>
        {% endfor %}

        </div>
        {% if request.user.profiles.all|length < 5 %}
      
            <div class="flex justify-center items-center">
                <a href="{% url 'core:profile_create' %}">
                    
                    <button class="px-4 py-2 rounded-md outline-none bg-gray-400 text-gray-100">
                        Add A New Profile
                    </button>
                </a>
            </div>
        {% endif %}
    </section>
{% endblock content %}

templates/showMovie.html
{% extends 'base.html' %}

{% block title %}
 Movie
{% endblock title %}

{% block others %}

    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
    <style>
        .player::-webkit-progress-bar{
            color: red;
        }
    </style>
{% endblock others%}
    
{% block content %}
    {% include 'partials/navbar.html' %}
    <main class='bg-primary_black h-full w-full '>
        {{ movie|json_script:"movie_data" }}

        <video src="#" controls class="w-full h-screen player"></video>
        
    </main>
    <script>
        const videoEl=document.querySelector('video')
        const movie_data = JSON.parse(document.getElementById('movie_data').textContent);
        
       
        const url =new URL(location.href)
        
        const video_param = parseInt(url.searchParams.get("epi")) ? parseInt(url.searchParams.get("epi")) : 0

        videoEl.setAttribute('src',`http://127.0.0.1:8000//media/${movie_data[video_param].file}`)
    </script>
{% endblock content %}